DWAPlannerROS:
#Robot Config Params
  acc_lim_theta: 1.0
  acc_lim_x: 1.0
  acc_lim_y: 0.0
  acc_limit_trans: 1.0
  max_vel_x: 0.2
  min_vel_x: -0.15 
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_trans_vel: 0.3
  min_trans_vel: 0.04
  max_rot_vel: 0.5
  min_rot_vel: 0.2
#Forward Simulation Parameters
  sim_time: 8
  sim_granularity: 0.05
  vx_samples: 10
  vy_samples: 1
  vth_samples: 35 
  penalize_negative_x: false
#Trajectory Scoring Parameters
  goal_distance_bias: 10.0
  path_distance_bias: 5.0
  occdist_scale: 30
  stop_time_buffer: 0.1
  forward_point_distance: 0.00
  scaling_speed: 0.2
  max_scaling_factor: 0.1
#Goal Tolerance Parameters
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: true
  rot_stopped_vel: 0.005
  trans_stopped_vel: 0.005
#Oscillation Prevention Param
  oscillation_reset_dist: 0.2
  oscillation_reset_angle: 0.2
#Global Plan PArameters
  prune_plan: false

recovery_behaviors: [{name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}, {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery}]

