controller_list:
  - name: /mico/mico_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - mico_joint_1
      - mico_joint_2
      - mico_joint_3
      - mico_joint_4
      - mico_joint_5
      - mico_joint_6
    
    constrains:
        goal_time: 0.5
        mico_joint_1:
            trajectory: 0.05
            goal: 0.02
        mico_joint_2:
            trajectory: 0.05
            goal: 0.02
        mico_joint_3:
            trajectory: 0.05
            goal: 0.02
        mico_joint_4:
            trajectory: 0.05
            goal: 0.02
        mico_joint_5:
            trajectory: 0.05
            goal: 0.02
        mico_joint_6:
            trajectory: 0.05
            goal: 0.02

  - name: /mico/mico_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - mico_joint_finger_1
      - mico_joint_finger_2

    constrains:
        goal_time: 0.5
        mico_joint_finger_1:
            trajectory: 0.05
            goal: 0.02
        mico_joint_finger_2:
            trajectory: 0.05
            goal: 0.02
        
