(cl:defpackage basic_exercises-msg
  (:use )
  (:export
   "<RESULTBAG>"
   "RESULTBAG"
   "<PIXELCOUNTACTIONRESULT>"
   "PIXELCOUNTACTIONRESULT"
   "<PIXELCOUNTACTIONGOAL>"
   "PIXELCOUNTACTIONGOAL"
   "<PIXELCOUNTFEEDBACK>"
   "PIXELCOUNTFEEDBACK"
   "<PIXELCOUNTACTION>"
   "PIXELCOUNTACTION"
   "<PIXELCOUNTACTIONFEEDBACK>"
   "PIXELCOUNTACTIONFEEDBACK"
   "<PIXELCOUNTGOAL>"
   "PIXELCOUNTGOAL"
   "<PIXELCOUNTRESULT>"
   "PIXELCOUNTRESULT"
  ))

