// Generated by gencpp from file basic_exercises/rgb2grey.msg
// DO NOT EDIT!


#ifndef BASIC_EXERCISES_MESSAGE_RGB2GREY_H
#define BASIC_EXERCISES_MESSAGE_RGB2GREY_H

#include <ros/service_traits.h>


#include <basic_exercises/rgb2greyRequest.h>
#include <basic_exercises/rgb2greyResponse.h>


namespace basic_exercises
{

struct rgb2grey
{

typedef rgb2greyRequest Request;
typedef rgb2greyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct rgb2grey
} // namespace basic_exercises


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::basic_exercises::rgb2grey > {
  static const char* value()
  {
    return "e17564393caa09204395429b782c4ee9";
  }

  static const char* value(const ::basic_exercises::rgb2grey&) { return value(); }
};

template<>
struct DataType< ::basic_exercises::rgb2grey > {
  static const char* value()
  {
    return "basic_exercises/rgb2grey";
  }

  static const char* value(const ::basic_exercises::rgb2grey&) { return value(); }
};


// service_traits::MD5Sum< ::basic_exercises::rgb2greyRequest> should match 
// service_traits::MD5Sum< ::basic_exercises::rgb2grey > 
template<>
struct MD5Sum< ::basic_exercises::rgb2greyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::basic_exercises::rgb2grey >::value();
  }
  static const char* value(const ::basic_exercises::rgb2greyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::basic_exercises::rgb2greyRequest> should match 
// service_traits::DataType< ::basic_exercises::rgb2grey > 
template<>
struct DataType< ::basic_exercises::rgb2greyRequest>
{
  static const char* value()
  {
    return DataType< ::basic_exercises::rgb2grey >::value();
  }
  static const char* value(const ::basic_exercises::rgb2greyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::basic_exercises::rgb2greyResponse> should match 
// service_traits::MD5Sum< ::basic_exercises::rgb2grey > 
template<>
struct MD5Sum< ::basic_exercises::rgb2greyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::basic_exercises::rgb2grey >::value();
  }
  static const char* value(const ::basic_exercises::rgb2greyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::basic_exercises::rgb2greyResponse> should match 
// service_traits::DataType< ::basic_exercises::rgb2grey > 
template<>
struct DataType< ::basic_exercises::rgb2greyResponse>
{
  static const char* value()
  {
    return DataType< ::basic_exercises::rgb2grey >::value();
  }
  static const char* value(const ::basic_exercises::rgb2greyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BASIC_EXERCISES_MESSAGE_RGB2GREY_H
