joint_limits:
  mico_elbow_roll_joint:
    has_velocity_limits: true
    max_velocity: 1.04719752
    has_acceleration_limits: false
    max_acceleration: 0
  mico_wrist_roll_joint:
    has_velocity_limits: true
    max_velocity: 1.04719752
    has_acceleration_limits: false
    max_acceleration: 0
  mico_hand_roll_joint:
    has_velocity_limits: true
    max_velocity: 1.04719752
    has_acceleration_limits: false
    max_acceleration: 0
  mico_elbow_pitch_joint:
    has_velocity_limits: true
    max_velocity: 0.837758016
    has_acceleration_limits: false
    max_acceleration: 0
  mico_shoulder_pitch_joint:
    has_velocity_limits: true
    max_velocity: 0.837758016
    has_acceleration_limits: false
    max_acceleration: 0
  mico_shoulder_yaw_joint:
    has_velocity_limits: true
    max_velocity: 0.837758016
    has_acceleration_limits: false
    max_acceleration: 0