mico:
  mico_arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - mico_joint_1
      - mico_joint_2
      - mico_joint_3
      - mico_joint_4
      - mico_joint_5
      - mico_joint_6

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    
  mico_hand_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - mico_joint_finger_1
      - mico_joint_finger_2

  hand_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
   
