// Generated by gencpp from file basic_exercises/pixelcountFeedback.msg
// DO NOT EDIT!


#ifndef BASIC_EXERCISES_MESSAGE_PIXELCOUNTFEEDBACK_H
#define BASIC_EXERCISES_MESSAGE_PIXELCOUNTFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace basic_exercises
{
template <class ContainerAllocator>
struct pixelcountFeedback_
{
  typedef pixelcountFeedback_<ContainerAllocator> Type;

  pixelcountFeedback_()
    {
    }
  pixelcountFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::basic_exercises::pixelcountFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::basic_exercises::pixelcountFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct pixelcountFeedback_

typedef ::basic_exercises::pixelcountFeedback_<std::allocator<void> > pixelcountFeedback;

typedef boost::shared_ptr< ::basic_exercises::pixelcountFeedback > pixelcountFeedbackPtr;
typedef boost::shared_ptr< ::basic_exercises::pixelcountFeedback const> pixelcountFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::basic_exercises::pixelcountFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::basic_exercises::pixelcountFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace basic_exercises

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'basic_exercises': ['/home/student/catkin_ws/src/basic_exercises/msg', '/home/student/catkin_ws/devel/share/basic_exercises/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::basic_exercises::pixelcountFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::basic_exercises::pixelcountFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::basic_exercises::pixelcountFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::basic_exercises::pixelcountFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::basic_exercises::pixelcountFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::basic_exercises::pixelcountFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::basic_exercises::pixelcountFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::basic_exercises::pixelcountFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::basic_exercises::pixelcountFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "basic_exercises/pixelcountFeedback";
  }

  static const char* value(const ::basic_exercises::pixelcountFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::basic_exercises::pixelcountFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
";
  }

  static const char* value(const ::basic_exercises::pixelcountFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::basic_exercises::pixelcountFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pixelcountFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::basic_exercises::pixelcountFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::basic_exercises::pixelcountFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // BASIC_EXERCISES_MESSAGE_PIXELCOUNTFEEDBACK_H
