// Generated by gencpp from file basic_exercises/pixelcountResult.msg
// DO NOT EDIT!


#ifndef BASIC_EXERCISES_MESSAGE_PIXELCOUNTRESULT_H
#define BASIC_EXERCISES_MESSAGE_PIXELCOUNTRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace basic_exercises
{
template <class ContainerAllocator>
struct pixelcountResult_
{
  typedef pixelcountResult_<ContainerAllocator> Type;

  pixelcountResult_()
    : count(0)  {
    }
  pixelcountResult_(const ContainerAllocator& _alloc)
    : count(0)  {
  (void)_alloc;
    }



   typedef int32_t _count_type;
  _count_type count;




  typedef boost::shared_ptr< ::basic_exercises::pixelcountResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::basic_exercises::pixelcountResult_<ContainerAllocator> const> ConstPtr;

}; // struct pixelcountResult_

typedef ::basic_exercises::pixelcountResult_<std::allocator<void> > pixelcountResult;

typedef boost::shared_ptr< ::basic_exercises::pixelcountResult > pixelcountResultPtr;
typedef boost::shared_ptr< ::basic_exercises::pixelcountResult const> pixelcountResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::basic_exercises::pixelcountResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::basic_exercises::pixelcountResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace basic_exercises

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'basic_exercises': ['/home/student/catkin_ws/src/basic_exercises/msg', '/home/student/catkin_ws/devel/share/basic_exercises/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::basic_exercises::pixelcountResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::basic_exercises::pixelcountResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::basic_exercises::pixelcountResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::basic_exercises::pixelcountResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::basic_exercises::pixelcountResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::basic_exercises::pixelcountResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::basic_exercises::pixelcountResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "602d642babe509c7c59f497c23e716a9";
  }

  static const char* value(const ::basic_exercises::pixelcountResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x602d642babe509c7ULL;
  static const uint64_t static_value2 = 0xc59f497c23e716a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::basic_exercises::pixelcountResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "basic_exercises/pixelcountResult";
  }

  static const char* value(const ::basic_exercises::pixelcountResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::basic_exercises::pixelcountResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
int32 count\n\
";
  }

  static const char* value(const ::basic_exercises::pixelcountResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::basic_exercises::pixelcountResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pixelcountResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::basic_exercises::pixelcountResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::basic_exercises::pixelcountResult_<ContainerAllocator>& v)
  {
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASIC_EXERCISES_MESSAGE_PIXELCOUNTRESULT_H
