controller_list:
  - name: fake_arm_controller
    joints:
      - mico_shoulder_yaw_joint
      - mico_shoulder_pitch_joint
      - mico_elbow_pitch_joint
      - mico_elbow_roll_joint
      - mico_wrist_roll_joint
      - mico_hand_roll_joint
  - name: fake_gripper_controller
    joints:
      - mico_hand_roll_joint
      - mico_finger_1_joint
      - mico_finger_2_joint
      - mico_finger_3_joint