controller_manager_ns: mico_controller_manager
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - mico_joint_1
      - mico_joint_2
      - mico_joint_3
      - mico_joint_4
      - mico_joint_5
      - mico_joint_6
      - mico_joint_base
