TrajectoryPlannerROS:

# Set the acc.eleration limits of the robot - "most important thing"
  acc_lim_x: 0.3                    # 2.5
  acc_lim_y: 0.0                   # 2.5
  acc_lim_theta: 1.0                  # 3.2

# Set the velocity limits of the robot
  max_vel_x: 0.5                   # 0.5
  min_vel_x: 0.10                   # 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.1  # 0.1

# Notice that this velocity is set to be negative. A bit confusing admittedly.
  escape_vel: -0.1                  # -0.1

# p2os is no holonomic robot.
  holonomic_robot: false            # false

# ---- Goal tolerance parameters
  yaw_goal_tolerance: 0.3           # 0.05
  xy_goal_tolerance: 0.2            # 0.1
  latch_xy_goal_tolerance: true     # false
  
# ---- Foward simulation parameters
# We'll configure how long and with what granularity we'll forward simulate trajectories  
  sim_time: 3.0                 # setting it higher can result in slightly smoother trajectories def:1   1.7
  sim_granularity: 0.05             # 0.025
  angular_sim_granularity: 0.05     # 0.025
  vx_samples: 6                    # 3
  vtheta_samples: 20                # 20
  controller_frequency: 5.0         # 20
  controller_patience: 3.0
  
  planner_frequency: 1.0
  planner_patience: 5.0
  
  oscilliation_timout: 10.0
  oscilliation_distance: 0.2

# ---- Parameters for scoring trajectories
  meter_scoring: true
  pdist_scale: 0.6           #   will make the robot follow the path more closely (if big) - default: 0.6
  gdist_scale: 0.8           # default: 0.8
  occdist_scale: 0.01              # weighting how much controller should avoid obstacles default: 0.01
  heading_lookahead: 0.325          # default 0.325m 
  #heading_scoring: false             # default false
  #heading_scoring_timestep: 0.1     # default 0.8 sec
  dwa: false                        # false if robot has low acceleration limits

# --- Oscillation prevention parameters
  oscillation_reset_dist: 0.05
  

# --- recovery behaviours 
 # recovery_behaviors: [{name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}, {name: rotate_recovery, type: rotate_recovery/RotateRecovery}]

      #DEFAULT: [{name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}, {name: rotate_recovery, type: rotate_recovery/RotateRecovery}, {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery}]

#conservative_reset_dist: 4.0


