obstacle_range: 2.5
raytrace_range: 3.0

#robot_radius: 0.35

footprint: [[-0.30, -0.3], [-0.30, 0.3], [0.3, 0.3], [0.3, -0.3]] # x: 60 cm, y: 60 cm
#footprint: [ [0.313, -0.18], [0.313, 0.18], [0.18, 0.2525], [-0.18, 0.2525], [-0.313, 0.18], [-0.313, -0.18], [-0.18, -0.2525], [0.18, -0.2525] ]
#footprint: [ [0.15, -0.25], [0.25, -0.195], [0.30, -0.1], [0.31, 0], [0.30, 0.1], [0.25, 0.195],  [0.15, 0.25], [-0.15, 0.25], [-0.25, 0.195], [-0.30, 0.1], [-0.31, 0], [-0.30, -0.1], [-0.25, -0.195], [-0.15, -0.25] ]

inflation_radius: 0.65
transform_tolerance: 0.5

observation_sources: point_cloud_sensor point_cloud_sensor2 laser_scan_sensor 

point_cloud_sensor: {sensor_frame: camera_link, data_type: PointCloud2, min_obstacle_height: 0.15, topic: voxel_grid/output, marking: true, clearing: false, expected_update_rate: 0.3}
point_cloud_sensor2: {sensor_frame: camera_link, data_type: PointCloud2, min_obstacle_height: 0.0, topic: voxel_grid/output, marking: false, clearing: true, expected_update_rate: 0.3}
laser_scan_sensor: {sensor_frame: laser_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

