global_costmap:
  global_frame: /map
  robot_base_frame: base_footprint
  observation_sources: point_cloud_sensor point_cloud_sensor2 laser_scan_sensor
  update_frequency: 5.0
  publish_frequency: 0.0
  static_map: true
  rolling_window: false
  footprint_padding: 0.02
  resolution: 0.05
