local_costmap:
  #publish_voxel_map: true
  global_frame: map
  robot_base_frame: base_footprint
  observation_sources: point_cloud_sensor point_cloud_sensor2 laser_scan_sensor
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 10
  height: 10
  #resolution: 0.05
